config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'parking_images/:id' => 'welcome#parking_images', as: :parking_images
  get 'mobile/parkings' => 'mobile#parkings'
  get 'feedback' => 'welcome#feedback', as: :feedback_modal

  resources :feedbacks, :only => [:create]

  namespace :administrator do
    resources :features, except: :show
    resources :parkings, :except => :show do
      # member do
      #   get :clone
      # end
      collection do
        get :process_active
        # post :process_checked_list
        # post :sort
        # get :set_price
      end
    end
    resources :sortable do
      collection do
        post :sort
      end
    end
    resources :slides, except: :show
    resources :feedbacks, except: :show
    resources :parking_images, :only => [:create] do
      get '/parking_image/destroy' => 'parking_images#destroy'
    end
    root 'parkings#index'
  end

  # get 'welcome' => 'welcome#index'
  # root 'welcome#cs'
  root 'welcome#index'
end

app/models/parking.rb
class Parking < ActiveRecord::Base
  default_scope { order('id ASC') }
  scope :active, -> { where(active: true) }
  has_many :parking_images, -> { order(:position) }, :dependent => :destroy, :inverse_of => :parking

  FILE_NAME = 'parking-full'
  ADDRESS = 'A'
  DESCRIPTION = 'B'
  AREA = 'D'
  PARK_TYPE = 'E'
  CAPACITY = 'F'
  LAT = 'H'
  LNG = 'I'
  LAT_ENTRY_1 = 'K'
  LNG_ENTRY_1 = 'L'
  LAT_ENTRY_2 = 'M'
  LNG_ENTRY_2 = 'N'
  INTERNAL_NUMBER = 'J'


  FIRST_LINE = 2

  SHEET_PARKINGS = 0
  SHEET_AREAS = 1
  SHEET_PARK_TYPE = 2

  def self.import_parking
    table_parkings = Roo::Excelx.new("public/#{FILE_NAME}.xlsx")
    sheet = table_parkings.sheets[SHEET_PARKINGS]

    FIRST_LINE.upto(table_parkings.last_row) do |line|
      parking_address = table_parkings.cell(line, ADDRESS, sheet) unless table_parkings.cell(line, ADDRESS, sheet).nil?
      parking_description = table_parkings.cell(line, DESCRIPTION, sheet) unless table_parkings.cell(line, DESCRIPTION, sheet).nil?
      parking_area = table_parkings.cell(line, AREA, sheet) unless table_parkings.cell(line, AREA, sheet).nil?
      parking_park_type = table_parkings.cell(line, PARK_TYPE, sheet) unless table_parkings.cell(line, PARK_TYPE, sheet).nil?
      parking_capacity = table_parkings.cell(line, CAPACITY, sheet) unless table_parkings.cell(line, CAPACITY, sheet).nil?
      parking_lat = table_parkings.cell(line, LAT, sheet) unless table_parkings.cell(line, LAT, sheet).nil?
      parking_lng = table_parkings.cell(line, LNG, sheet) unless table_parkings.cell(line, LNG, sheet).nil?
      parking_lat_entry_1 = table_parkings.cell(line, LAT_ENTRY_1, sheet) unless table_parkings.cell(line, LAT_ENTRY_1, sheet).nil?
      parking_lng_entry_1 = table_parkings.cell(line, LNG_ENTRY_1, sheet) unless table_parkings.cell(line, LNG_ENTRY_1, sheet).nil?
      parking_lat_entry_2 = table_parkings.cell(line, LAT_ENTRY_2, sheet) unless table_parkings.cell(line, LAT_ENTRY_2, sheet).nil?
      parking_lng_entry_2 = table_parkings.cell(line, LNG_ENTRY_2, sheet) unless table_parkings.cell(line, LNG_ENTRY_2, sheet).nil?
      parking_internal_number = table_parkings.cell(line, INTERNAL_NUMBER, sheet) unless table_parkings.cell(line, INTERNAL_NUMBER, sheet).nil?

      parking = Parking.create(address: parking_address,
                               description: parking_description,
                               area: Area.by_name(parking_area),
                               park_type: ParkingType.code_by_name(parking_park_type),
                               capacity: parking_capacity,
                               lat: parking_lat,
                               lng: parking_lng,
                               lat_entry_1: parking_lat_entry_1,
                               lng_entry_1: parking_lng_entry_1,
                               lat_entry_2: parking_lat_entry_2,
                               lng_entry_2: parking_lng_entry_2,
                               internal_number: parking_internal_number,
      )
      parking.save!
    end
  end

  def update_image_title(hash_image)
    unless hash_image
      return
    end
    hash_image.keys.each do |key|
      image = ParkingImage.find key
      if image.parking_id.nil?
        image = ParkingImage.find key
        image.parking_id = self.id
      end
      image.title = hash_image[key]
      image.save
    end
  end

end

app/models/parking_type.rb
#encoding: utf-8
# Синяя	Официально бесплатная парковка
# Зеленая	Объекты, на которых можно свободно парковаться, т.к. платной парковки в округе нет
# Желтая	Объекты, на которых можно свободно парковаться, т.к. платной парковки в округе нет
# Красная	Популярное место для парковки, но противозаконное и с высокой вероятностью эвакуации
class ParkingType
  attr_accessor :name
  attr_accessor :code
  attr_accessor :description

  def self.collection
    [
        ParkingType.new(name: 'Синяя', description: 'Официально бесплатная парковка', code: 1),
        ParkingType.new(name: 'Зеленая', description: 'Объекты, на которых можно свободно парковаться, т.к. платной парковки в округе нет', code: 2),
        ParkingType.new(name: 'Желтая', description: 'Объекты, на которых можно свободно парковаться, т.к. платной парковки в округе нет', code: 3),
        ParkingType.new(name: 'Красная', description: 'Популярное место для парковки, но противозаконное и с высокой вероятностью эвакуации', code: 4)
    ]
  end

  def self.include?(code)
    collection.each do |role|
      return true if role.code == code
    end
    false
  end

  def self.code_by_name(name)
    collection.each do |value|
      return value.code if value.name == name
    end
    false
  end

  def self.by_code(code)
    collection.each do |value|
      return value.name if value.code == code
    end
    false
  end

  def initialize(hash)
    self.name = hash[:name]
    self.code = hash[:code]
    self.description = hash[:description]
  end

end

app/controllers/administrator/common_controller.rb
class Administrator::CommonController < InheritedResources::Base

  before_filter :authenticate_user!
  before_action :check_administrator?

  layout 'administrator'

  #index, show, new, edit, create, update, destroy

  actions :all, :except => :show
  respond_to :html, only: [:index]
  respond_to :js, except: [:index]
  #respond_to :html, :xml, :json, :js

  # def create
  #   super do |format|
  #     format.html { redirect_to administrator_categories_path }
  #   end
  # end
  # # redirect to *index* instead of *show* by default
  # def create
  #   create! { collection_path }
  # end
  # def update
  #   update! { collection_path }
  # end
  # private
  # def i18n_name
  #   resource_class.name.underscore
  # end

  protected

  def check_administrator?
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/administrator/features_controller.rb
class Administrator::FeaturesController < Administrator::CommonController

  private

  def feature_params
    params.require(:feature).permit(:title, :description, :image, :position)
  end
end

app/controllers/administrator/feedbacks_controller.rb
class Administrator::FeedbacksController < Administrator::CommonController

  private

    def feedback_params
      params.require(:feedback).permit(:name, :email, :feedback_type, :comment, :mobile_phone)
    end
end

app/controllers/administrator/parking_images_controller.rb
class Administrator::ParkingImagesController < ActionController::Base

  def create

    file    = params[:file].tempfile
    # klass   = Object.const_get params[:obj]

    # @object  = klass.create(parking_id: params[:parking_id])
    # @object.image     = params[:file]
    # @object.save!

    @image = ParkingImage.create(parking_id: params[:parking_id])
    @image.image     = params[:file]
    @image.save!

    path_file = params[:file].path
    file.close
    File.delete(path_file)

    render 'administrator/parkings/return_parking_image', image: @image

    rescue Exception => e
      render :text => "{error:#{e.message}}"
  end

  def destroy
    @image = ParkingImage.find(params[:parking_image_id])
    system("rm -rf #{Rails.root}/public/catalog/parking_image/#{@image.id}")
    @image.delete
  end

end

app/controllers/administrator/parkings_controller.rb
class Administrator::ParkingsController < Administrator::CommonController

  def update
    super
    @parking.update_image_title params[:parking_image]
  end

  def process_active
    parking = Parking.find(params[:parking])
    parking.update_attribute(:active, params[:checked])
    parking.touch
    render :nothing => true, :status => 200
  end

  private

  def parking_params
    params.require(:parking).permit(:internal_number,
                                    :address,
                                    :description,
                                    :area,
                                    :park_type,
                                    :capacity,
                                    :active,
                                    :lat,
                                    :lng,
                                    :lat_entry_1,
                                    :lng_entry_1,
                                    :lat_entry_2,
                                    :lng_entry_2)
  end
end

app/controllers/administrator/slides_controller.rb
class Administrator::SlidesController < Administrator::CommonController

  private

    def slide_params
      params.require(:slide).permit(:inside, :image, :position)
    end
end

app/controllers/administrator/sortable_controller.rb
class Administrator::SortableController < ApplicationController

  def sort
    if params['SortElement']
      klass   = Object.const_get params[:obj]
      object  = klass.find(params[:SortElement][:id].to_i)
      object2 = klass.find(params[:SortElement][:id2].to_i)
      object.insert_at(if object2.position then object2.position else 0 end)
      object.save
      render :nothing => true, :status => 200
    end
  end

end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/administrator/parkings/_edit.html.haml
%div.row
  <a class="close-reveal-modal" id="click_administrator_modal_close">&#215;</a>
  %h1
    =t('helpers.title.edit', :model => t('activerecord.changed_model.parking'))
  =render 'administrator/parkings/form'

app/views/administrator/parkings/_form.html.haml
=simple_form_for [:administrator, @parking], remote: true  do |f|
  =f.input :internal_number
  =f.input :address
  =f.input :description
  =f.input :capacity
  =collection_select :parking, :area, Area.collection, :code, :name, selected: @parking.area
  =collection_select :parking, :park_type, ParkingType.collection, :code, :description, selected: @parking.park_type
  %div.row
    =f.input :lat, wrapper_html: {class:"medium-4 columns"}
    =f.input :lat_entry_1, wrapper_html: {class:"medium-4 columns"}
    =f.input :lat_entry_2, wrapper_html: {class:"medium-4 columns"}
  %div.row
    =f.input :lng, wrapper_html: {class:"medium-4 columns"}
    =f.input :lng_entry_1, wrapper_html: {class:"medium-4 columns"}
    =f.input :lng_entry_2, wrapper_html: {class:"medium-4 columns"}
  %div{class:"large-12 columns load-image-block", id:"file-uploader-parking-image"}
    Нажмите для выбора файла или перетащите изображение
  =render 'parking_image_upload', parking: @parking
  =f.button :submit, class: "button"

app/views/administrator/parkings/_new.html.haml
%div.row
  <a class="close-reveal-modal" id="click_administrator_modal_close">&#215;</a>
  %h1
    =t("helpers.title.new", :model => t("activerecord.changed_model.parking"))
  =render 'form'

app/views/administrator/parkings/_parking_image.html.haml
%li{id:"uploaded-ParkingImage", data:{model:{id:"#{parking_image.id}"}, obj:"ParkingImage"} }
  %div{class:"parking-image-sort row", id: "ParkingImage_#{parking_image.id}"}
    %div{ data:{dz:{thumbnail:''}} }
      %div{class:"large-2 columns", style:'width:100px;'}
        =image_tag parking_image.image_url(:list_preview)
      %div{class:"large-9 columns"}
        Подпись изображения
        =text_field_tag "parking_image[#{parking_image.id}]", parking_image.title
      %div{class:"large-1 columns ad_top_pad", style:'padding:30px;'}
        =link_to "<i tabindex='0' class='fa fa-remove 2x'></i>".html_safe, "/administrator/parking_images/#{parking_image.id}/parking_image/destroy", remote: true

app/views/administrator/parkings/_parking_image_upload.html.haml
-#%hr
-if parking.parking_images.count > 0
  %h2
    Загруженные
%ui{id:"sort-paking-image",class:"image-sort"}
  -parking.parking_images.each do |parking_image|
    =render 'parking_image', parking_image: parking_image

  :javascript
    var imgDropzone = new Dropzone("div#file-uploader-parking-image", {
      url: "/administrator/parking_images",
      method: 'post',
      params: {"parking_id":"#{parking.id}"},
      acceptedFiles: ".jpg, .jpeg, .gif, .png, .JPG, .JPEG, .GIF, .PNG",
      error: function (file, error) {
        imgDropzone.removeFile( file );
      },
      addedfile: function(file) { return true;},
      success: function(file, data) {
        $("#sort-paking-image").append(data.image);
      }
    });
    InitSortable("ui#sort-paking-image");

app/views/administrator/parkings/_parking_row.html.haml
%tr{id:parking.id}
  %td.large-1.columns
    =image_tag "parking_type/#{parking.park_type}.png"
  %td.large-2.columns
    =parking.internal_number
  %td.large-2.columns
    =Area.by_code(parking.area)
  %td.large-3.columns
    =parking.address
  %td.large-1.columns
    =parking.capacity
  %td.large-1.columns
    =check_box_tag 'show_parkings[]', parking.id, false, class: 'checked-list checked-all-active', checked: parking.active, onclick:'processParkingActive(this)'
  %td.large-1.columns
    =link_to '<i class="fa fa-edit"></i>'.html_safe, edit_administrator_parking_path(parking), remote: true
  %td.large-1.columns
    =link_to '<i class="fa fa-remove"></i>'.html_safe, administrator_parking_path(parking), method: :delete, data: { confirm: 'Are you sure?' }, remote: true

app/views/administrator/parkings/create.js.erb
$('#administrator_modal').html('<%= escape_javascript content_tag :h2, t("backend.actions.success_update", :model => t("activerecord.capitalized_model.parking")) %><a class="close-reveal-modal" id="click_administrator_modal_close">&#215;</a>');
setTimeout(function () {
    $('#click_administrator_modal_close').trigger('click');
}, 1000);

$('#parkings > tbody').append('<%= escape_javascript render 'administrator/parkings/parking_row', parking: @parking %>');

$('#administrator_alert > h2').html('<%= t("backend.actions.success_create", :model => t("activerecord.changed_model.parking")) %>');
$('#click_administrator_alert').trigger('click');
setTimeout(function () {
    $('#click_administrator_alert_close').trigger('click');
}, 1000);

app/views/administrator/parkings/destroy.js.erb
$("#<%= @parking.id %>").remove();

app/views/administrator/parkings/edit.js.erb
$('#administrator_modal').html('<%= escape_javascript render 'administrator/parkings/edit' %>');
$('#click_administrator_modal').trigger('click');

app/views/administrator/parkings/index.html.haml
%div.row
  %div{class:"custom-panel"}
    %div{class:"custom-panel-heading"}
      %h4
        =t("helpers.title.list", :model => t("activerecord.list_multiple_model.parking"))
        =link_to '<i class="fa fa-plus cat-plus"></i>'.html_safe, new_administrator_parking_path, remote: true
      %table#parkings
        %thead
          %td.large-1.columns
            Тип парковки
          %td.large-2.columns
            Служебный номер
          %td.large-2.columns
            Район
          %td.large-3.columns
            Адрес
          %td.large-1.columns
            Вместимость
          %td.large-1.columns
            Отображать
          %td.large-1.columns
            Редактировать
          %td.large-1.columns
            Удалить
        %tbody
          -@parkings.each do |parking|
            =render 'administrator/parkings/parking_row', parking: parking

app/views/administrator/parkings/new.js.erb
$('#administrator_modal').html('<%= escape_javascript render 'administrator/parkings/new' %>');
$('#click_administrator_modal').trigger( 'click' );
//$(function () {
//    $('#parking_description').redactor({
//        lang: 'ru',
//        buttons: ['html', 'formatting', 'bold', 'unorderedlist'],
//        cleanSpaces: true
//    });
//});

app/views/administrator/parkings/update.js.erb
$('#administrator_modal').html('<%= escape_javascript content_tag :h2, t("backend.actions.success_update", :model => t("activerecord.capitalized_model.parking")) %><a class="close-reveal-modal" id="click_administrator_modal_close">&#215;</a>');
setTimeout(function () {
    $('#click_administrator_modal_close').trigger('click');
}, 1000);
$('#<%= @parking.id %>').replaceWith('<%= escape_javascript render 'administrator/parkings/parking_row', parking: @parking %>');