config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'parking_images/:id' => 'welcome#parking_images', as: :parking_images
  get 'mobile/parkings' => 'mobile#parkings'
  get 'feedback' => 'welcome#feedback', as: :feedback_modal

  resources :feedbacks, :only => [:create]

  namespace :administrator do
    resources :features, except: :show
    resources :parkings, :except => :show do
      # member do
      #   get :clone
      # end
      collection do
        get :process_active
        # post :process_checked_list
        # post :sort
        # get :set_price
      end
    end
    resources :sortable do
      collection do
        post :sort
      end
    end
    resources :slides, except: :show
    resources :feedbacks, except: :show
    resources :parking_images, :only => [:create] do
      get '/parking_image/destroy' => 'parking_images#destroy'
    end
    root 'parkings#index'
  end

  # get 'welcome' => 'welcome#index'
  # root 'welcome#cs'
  root 'welcome#index'
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/administrator/common_controller.rb
class Administrator::CommonController < InheritedResources::Base

  before_filter :authenticate_user!
  before_action :check_administrator?

  layout 'administrator'

  #index, show, new, edit, create, update, destroy

  actions :all, :except => :show
  respond_to :html, only: [:index]
  respond_to :js, except: [:index]
  #respond_to :html, :xml, :json, :js

  # def create
  #   super do |format|
  #     format.html { redirect_to administrator_categories_path }
  #   end
  # end
  # # redirect to *index* instead of *show* by default
  # def create
  #   create! { collection_path }
  # end
  # def update
  #   update! { collection_path }
  # end
  # private
  # def i18n_name
  #   resource_class.name.underscore
  # end

  protected

  def check_administrator?
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/administrator/features_controller.rb
class Administrator::FeaturesController < Administrator::CommonController

  private

  def feature_params
    params.require(:feature).permit(:title, :description, :image, :position)
  end
end

app/controllers/administrator/feedbacks_controller.rb
class Administrator::FeedbacksController < Administrator::CommonController

  private

    def feedback_params
      params.require(:feedback).permit(:name, :email, :feedback_type, :comment, :mobile_phone)
    end
end

app/controllers/administrator/parking_images_controller.rb
class Administrator::ParkingImagesController < ActionController::Base

  def create

    file    = params[:file].tempfile
    # klass   = Object.const_get params[:obj]

    # @object  = klass.create(parking_id: params[:parking_id])
    # @object.image     = params[:file]
    # @object.save!

    @image = ParkingImage.create(parking_id: params[:parking_id])
    @image.image     = params[:file]
    @image.save!

    path_file = params[:file].path
    file.close
    File.delete(path_file)

    render 'administrator/parkings/return_parking_image', image: @image

    rescue Exception => e
      render :text => "{error:#{e.message}}"
  end

  def destroy
    @image = ParkingImage.find(params[:parking_image_id])
    system("rm -rf #{Rails.root}/public/catalog/parking_image/#{@image.id}")
    @image.delete
  end

end

app/controllers/administrator/parkings_controller.rb
class Administrator::ParkingsController < Administrator::CommonController

  def update
    super
    @parking.update_image_title params[:parking_image]
  end

  def process_active
    parking = Parking.find(params[:parking])
    parking.update_attribute(:active, params[:checked])
    parking.touch
    render :nothing => true, :status => 200
  end

  private

  def parking_params
    params.require(:parking).permit(:internal_number,
                                    :address,
                                    :description,
                                    :area,
                                    :park_type,
                                    :capacity,
                                    :active,
                                    :lat,
                                    :lng,
                                    :lat_entry_1,
                                    :lng_entry_1,
                                    :lat_entry_2,
                                    :lng_entry_2)
  end
end

app/controllers/administrator/slides_controller.rb
class Administrator::SlidesController < Administrator::CommonController

  private

    def slide_params
      params.require(:slide).permit(:inside, :image, :position)
    end
end

app/controllers/administrator/sortable_controller.rb
class Administrator::SortableController < ApplicationController

  def sort
    if params['SortElement']
      klass   = Object.const_get params[:obj]
      object  = klass.find(params[:SortElement][:id].to_i)
      object2 = klass.find(params[:SortElement][:id2].to_i)
      object.insert_at(if object2.position then object2.position else 0 end)
      object.save
      render :nothing => true, :status => 200
    end
  end

end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/administrator/features/_edit.html.haml
%div.row
  <a class="close-reveal-modal" id="click_administrator_modal_close">&#215;</a>
  %h1
    =t('helpers.title.edit', :model => t('activerecord.changed_model.parking'))
  =render 'administrator/features/form'

app/views/administrator/features/_feature_row.html.haml
%tr{id:feature.id}
  %td.large-1.columns
    =image_tag feature.image_url(:thumb)
  %td.large-9.columns
    =feature.title
  %td.large-1.columns
    =link_to '<i class="fa fa-edit"></i>'.html_safe, edit_administrator_feature_path(feature), remote: true
  %td.large-1.columns
    =link_to '<i class="fa fa-remove"></i>'.html_safe, administrator_feature_path(feature), method: :delete, data: { confirm: 'Are you sure?' }, remote: true

app/views/administrator/features/_form.html.haml
=simple_form_for [:administrator, @feature], remote: true  do |f|
  =f.input :title
  =f.input :description
  =f.input :image, as: :file
  =f.button :submit, class: "button"
=image_tag @feature.image_url(:thumb) #unless @project_slides.image.nil?
:javascript
  $(function () {
      $('#feature_description').redactor({
          lang: 'ru',
          buttons: ['html', 'formatting', 'bold', 'unorderedlist'],
          cleanSpaces: true
      });
  });

app/views/administrator/features/_new.html.haml
%div.row
  <a class="close-reveal-modal" id="click_administrator_modal_close">&#215;</a>
  %h1
    =t("helpers.title.new", :model => t("activerecord.changed_model.feature"))
  =render 'form'

app/views/administrator/features/create.js.erb
$('#administrator_modal').html('<%= escape_javascript content_tag :h2, t("backend.actions.success_create", :model => t("activerecord.capitalized_model.feature")) %><a class="close-reveal-modal" id="click_administrator_modal_close">&#215;</a>');
setTimeout(function () {
    $('#click_administrator_modal_close').trigger('click');
}, 1000);

$('#feature > tbody').append('<%= escape_javascript render 'administrator/features/feature_row', feature: @feature %>');

$('#administrator_alert > h2').html('<%= t("backend.actions.success_create", :model => t("activerecord.changed_model.feature")) %>');
$('#click_administrator_alert').trigger('click');
setTimeout(function () {
    $('#click_administrator_alert_close').trigger('click');
}, 1000);

app/views/administrator/features/destroy.js.erb
$("#<%= @feature.id %>").remove();

app/views/administrator/features/edit.js.erb
$('#administrator_modal').html('<%= escape_javascript render 'administrator/features/edit' %>');
$('#click_administrator_modal').trigger('click');

app/views/administrator/features/index.html.haml
%div.row
  %div{class:"custom-panel"}
    %div{class:"custom-panel-heading"}
      %h4
        =t("helpers.title.list", :model => t("activerecord.list_multiple_model.feature"))
        =link_to '<i class="fa fa-plus cat-plus"></i>'.html_safe, new_administrator_feature_path, remote: true

      %table#feature
        %thead
          %td.large-1.columns
            Изображение
          %td.large-9.columns
            Заголовок
          %td.large-1.columns
            Редактировать
          %td.large-1.columns
            Удалить
        %tbody
          -@features.each do |feature|
            =render 'administrator/features/feature_row', feature: feature

app/views/administrator/features/new.js.erb
$('#administrator_modal').html('<%= escape_javascript render 'administrator/features/new' %>');
$('#click_administrator_modal').trigger( 'click' );
//$(function () {
//    $('#parking_description').redactor({
//        lang: 'ru',
//        buttons: ['html', 'formatting', 'bold', 'unorderedlist'],
//        cleanSpaces: true
//    });
//});

app/views/administrator/features/update.js.erb
$('#administrator_modal').html('<%= escape_javascript content_tag :h2, t("backend.actions.success_update", :model => t("activerecord.capitalized_model.feature")) %><a class="close-reveal-modal" id="click_administrator_modal_close">&#215;</a>');
setTimeout(function () {
    $('#click_administrator_modal_close').trigger('click');
}, 1000);
$('#<%= @feature.id %>').replaceWith('<%= escape_javascript render 'administrator/features/feature_row', feature: @feature %>');